on: push
name: make all
jobs:
  makeall:
    name: make all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: make all
      uses: docker://golang:latest
      with:
        entrypoint: bash
        args: -c "make all GOFLAGS=-buildvcs=false"
    - uses: actions/setup-go@v3
    - uses: docker/setup-buildx-action@v2
    - name: e2e
      run: |
        GOBIN=$HOME/.local/bin go install github.com/ricardobranco777/simplepki
        bash -x tests/e2e.sh
